import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";
import NavBar from "./components/layouts/NavBar";

const alexandria = Alexandria({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${alexandria.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
